"""primera db

Revision ID: 900910b5ee3c
Revises: 
Create Date: 2026-07-01 14:33:32.576512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '900910b5ee3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competiciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('ambito', sa.String(length=100), nullable=False),
    sa.Column('es_clubes', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('es_club', sa.Boolean(), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_nombre'), 'grupos', ['nombre'], unique=True)
    op.create_table('temporadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_nombre_usuario'), 'usuarios', ['nombre_usuario'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operacion', sa.Enum('create', 'update', 'delete', name='operacion_enum'), nullable=False),
    sa.Column('tabla', sa.Enum('usuario', 'grupo', 'usuario_grupo', 'temporada', 'jornada', 'premio', 'competicion', 'temporada_competicion', 'equipo', 'equipo_temporada_competicion', 'partido', 'apuesta', 'columna', 'pronostico', 'mensaje', name='tabla_enum'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jornadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha_cierre'),
    sa.UniqueConstraint('temporada_id', 'nombre', name='uq_jornada_temporada_nombre')
    )
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('enviado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temporadas_competiciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.Column('competicion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competicion_id'], ['competiciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('temporada_id', 'competicion_id', name='uq_temporada_competicion')
    )
    op.create_table('usuarios_grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('es_lider', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grupo_id', 'usuario_id', name='uq_usuario_grupo')
    )
    op.create_index('uq_grupo_lider', 'usuarios_grupos', ['grupo_id'], unique=True, postgresql_where='es_lider = true')
    op.create_table('apuestas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_elige8_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'cerrada', 'en_curso', 'finalizada', name='estado_apuesta_enum'), nullable=False),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('beneficio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_elige8_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jornada_id', 'grupo_id', name='uq_apuesta_jornada_grupo')
    )
    op.create_table('equipos_temporadas_competiciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('temporada_competicion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['temporada_competicion_id'], ['temporadas_competiciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipo_id', 'temporada_competicion_id', name='uq_equipo_temporada_competicion')
    )
    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('competicion_temporada_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canal', sa.String(length=100), nullable=True),
    sa.Column('equipo_local_id', sa.Integer(), nullable=True),
    sa.Column('equipo_visitante_id', sa.Integer(), nullable=True),
    sa.Column('goles_local', sa.Integer(), nullable=True),
    sa.Column('goles_visitante', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competicion_temporada_id'], ['temporadas_competiciones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipo_local_id'], ['equipos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipo_visitante_id'], ['equipos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jornada_id', 'orden', name='uq_partido_jornada_orden')
    )
    op.create_table('premios_jornada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.Enum('ACIERTOS_15', 'ACIERTOS_14', 'ACIERTOS_13', 'ACIERTOS_12', 'ACIERTOS_11', 'ACIERTOS_10', 'ELIGE_8', name='categoria_premio_enum'), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jornada_id', 'categoria', name='uq_premio_jornada_categoria')
    )
    op.create_table('columnas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apuesta_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('es_elige8', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['apuesta_id'], ['apuestas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_apuesta_elige8', 'columnas', ['apuesta_id'], unique=True, postgresql_where='es_elige8 = true')
    op.create_table('pronosticos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('columna_id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.Column('signo', sa.Enum('UNO', 'X', 'DOS', name='signo_enum'), nullable=True),
    sa.Column('pleno15_local', sa.Enum('CERO', 'UNO', 'DOS', 'M', name='goles_enum'), nullable=True),
    sa.Column('pleno15_visitante', sa.Enum('CERO', 'UNO', 'DOS', 'M', name='goles_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['columna_id'], ['columnas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('columna_id', 'partido_id', name='uq_pronostico_columna_partido')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pronosticos')
    op.drop_index('uq_apuesta_elige8', table_name='columnas', postgresql_where='es_elige8 = true')
    op.drop_table('columnas')
    op.drop_table('premios_jornada')
    op.drop_table('partidos')
    op.drop_table('equipos_temporadas_competiciones')
    op.drop_table('apuestas')
    op.drop_index('uq_grupo_lider', table_name='usuarios_grupos', postgresql_where='es_lider = true')
    op.drop_table('usuarios_grupos')
    op.drop_table('temporadas_competiciones')
    op.drop_table('mensajes')
    op.drop_table('jornadas')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_usuarios_nombre_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('temporadas')
    op.drop_index(op.f('ix_grupos_nombre'), table_name='grupos')
    op.drop_table('grupos')
    op.drop_table('equipos')
    op.drop_table('competiciones')
    # ### end Alembic commands ###
